networks:
  dto-red:
    ipam: 
      driver: default
      config: 
        - subnet: "192.168.0.0/24"
services:
  db:
    #razones del porque no usar siempre la version latest
    image: mysql:9.1.0
    #linea nueva
    container_name: base_datosPC
    environment:
      - MYSQL_DATABASE=limon_website
      - MYSQL_ROOT_PASSWORD=12345
    ports:
      - 3307:3306
    volumes:
      - ./mysql:/var/lib/mysql
      - ./db-dump:/docker-entrypoint-initdb.d
    networks:
      dto-red:
        ipv4_address: "192.168.0.10"
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadminPC
    ports:
      - 8080:80
    environment:
      - PMA_HOST=db
      - PMA_PORT=3306
    depends_on:
      - db
    networks:
      dto-red:
        ipv4_address: "192.168.0.11"
  web-datos:
    container_name: servidor-datosPC
    volumes:
      - ./datos/src:/var/www/html/src
      - ./datos/public:/var/www/html/public
      #- ./datos:/var/www/html/
    build:
      context: .
      dockerfile: ./datos/DockerFile
    ports:
      - 8000:80
    depends_on:
      - db 
    networks:
      dto-red:
        ipv4_address: "192.168.0.12"
  web-negocio:
    container_name: servidor-negocioPC
    volumes:
      - ./negocio/src:/var/www/html/src
      - ./negocio/public:/var/www/html/public
      #- ./www:/var/www/html/
    build:
      context: .
      dockerfile: ./negocio/DockerFile
    ports:
      - 9000:80
    depends_on:
      - web-datos
    networks:
      dto-red:
       ipv4_address: "192.168.0.13"
  # web-presentacion:
  #   container_name: servidor-presentacionPC
  #   build:
  #     context: .
  #     dockerfile: ./presentacion/DockerFile
  #   ports:
  #     - 80:80
  #   depends_on:
  #     - web-negocio
  #   networks:
  #     dto-red:
  #      ipv4_address: "192.168.0.14"
secrets:
  db_password:
    file: db_password.txt
volumes:
  db-dump: 
  mysql:
  datos:
  negocio: